####  Reference Documentation

In [126]:
# https://github.com/MicrosoftDocs/azure-ai-docs/blob/main/articles/ai-services/language-service/custom-named-entity-recognition/how-to/call-api.md#tab/client
# https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_custom_entities.py
# https://learn.microsoft.com/en-us/python/api/overview/azure/ai-textanalytics-readme?view=azure-python
# https://learn.microsoft.com/en-us/azure/ai-services/language-service/summarization/quickstart?tabs=text-summarization%2Cwindows&pivots=programming-language-python

####  Loading Libraries and clients

In [84]:
import os
import json
import time
import openai
import requests
import tiktoken
import pandas as pd
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient
from langchain.text_splitter import MarkdownHeaderTextSplitter
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest, ContentFormat
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest, DocumentAnalysisFeature

from azure.ai.textanalytics import (
    TextAnalyticsClient,
    ExtractiveSummaryAction,
    AbstractiveSummaryAction,
) 

from dotenv import load_dotenv
from openai import AzureOpenAI
load_dotenv(override=True)

aoai_client = AzureOpenAI(
  azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"), 
  api_key=os.getenv("AZURE_OPENAI_API_KEY"),  
  api_version="2024-07-01-preview"
)

AZURE_LANGUAGE_ENDPOINT = os.environ["AZURE_LANGUAGE_ENDPOINT"]
AZURE_LANGUAGE_KEY = os.environ["AZURE_LANGUAGE_KEY"]
CUSTOM_ENTITIES_PROJECT_NAME = os.environ["CUSTOM_ENTITIES_PROJECT_NAME"]
CUSTOM_ENTITIES_DEPLOYMENT_NAME = os.environ["CUSTOM_ENTITIES_DEPLOYMENT_NAME"]

# Text Analytics Client
text_analytics_client = TextAnalyticsClient(
    endpoint=AZURE_LANGUAGE_ENDPOINT,
    credential=AzureKeyCredential(AZURE_LANGUAGE_KEY),
)

# Document Intelligence Client
AZURE_DOC_INTELLIGENCE_ENDPOINT = os.environ["AZURE_DOC_INTELLIGENCE_ENDPOINT"]
AZURE_DOC_INTELLIGENCE_KEY = os.environ["AZURE_DOC_INTELLIGENCE_KEY"]
document_intelligence_client = DocumentIntelligenceClient(endpoint=AZURE_DOC_INTELLIGENCE_ENDPOINT, credential=AzureKeyCredential(AZURE_DOC_INTELLIGENCE_KEY), api_version="2024-07-31-preview")

# Azure OpenAI Client
aoai_client = AzureOpenAI(
  azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"), 
  api_key=os.getenv("AZURE_OPENAI_API_KEY"),  
  api_version="2024-07-01-preview"
)

#### Document Intelligence OCR

In [85]:
def text_html_processing(OcrExtractionDIOutput):
    offset = 0
    page_map = []
    page_map_dict =[]

    for page_num, page in enumerate(OcrExtractionDIOutput.pages):
        tables_on_page = [
            table
            for table in (OcrExtractionDIOutput.tables or [])
            if table.bounding_regions and table.bounding_regions[0].page_number == page_num + 1
        ]
        #print(tables_on_page)

        # mark all positions of the table spans in the page
        page_offset = page.spans[0].offset
        page_length = page.spans[0].length
        table_chars = [-1] * page_length
        for table_id, table in enumerate(tables_on_page):
            for span in table.spans:
                # replace all table spans with "table_id" in table_chars array
                for i in range(span.length):
                    idx = span.offset - page_offset + i
                    if idx >= 0 and idx < page_length:
                        table_chars[idx] = table_id

        # build page text by replacing characters in table spans with table html
        page_text = ""
        added_tables = set()
        for idx, table_id in enumerate(table_chars):
            if table_id == -1:
                page_text += OcrExtractionDIOutput.content[page_offset + idx]
            elif table_id not in added_tables:
                page_text += table_to_html(tables_on_page[table_id])
                added_tables.add(table_id)

        page_text += " "
        page_map.append((page_num+1, offset, page_text))

        single_page_dict = {}
        single_page_dict['page_num']= page_num+1
        single_page_dict['content'] = page_text
        single_page_dict['offset'] = offset
        page_map_dict.append(single_page_dict)

        offset += len(page_text)

    return page_map_dict

In [86]:
def OcrExtractionDI(relative_path: str, Markdown: [bool]=True):
    
    path_to_document = os.path.abspath(
        os.path.join(relative_path))
    
    if Markdown==True:
        output_format = ContentFormat.MARKDOWN
    else:
        output_format = None

    with open(path_to_document, "rb") as f:
        poller = document_intelligence_client.begin_analyze_document("prebuilt-layout", 
                                                                    analyze_request=f, content_type="application/octet-stream", 
                                                                    output_content_format=output_format)
    OcrExtractionDIOutput = poller.result()
    
    if Markdown==False:
        pagemap = text_html_processing(OcrExtractionDIOutput)
        extracted_processed_text = pagemap
    else:
        extracted_processed_text = OcrExtractionDIOutput

    return extracted_processed_text

In [87]:
def MdFormatting(ocr_extraction):
    doc_string = ocr_extraction.content

    ## Split the document into chunks base on markdown headers.
    headers_to_split_on = [
        ("#", "Title"),
        ("##", "Header 1"),
        ("###", "Header 2"),
        ("####", "Header 3"),
        ("#####", "Header 4"),
        ("######", "Header 5"),
        ("#######", "Header 6"),
    ]
    text_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)

    markdown_chunks = text_splitter.split_text(doc_string)

    chunk_list = []
    for chunk in markdown_chunks:
        try:
            title = chunk.metadata['Title']
        except:
            title = ""
        try:
            header1 = chunk.metadata['Header 1']
        except:
            header1 = ""
        try:
            header2 = chunk.metadata['Header 2']
        except:
            header2 = ""
        try:
            header3 = chunk.metadata['Header 3']
        except:
            header3 = ""    

        chunk_list.append({"title": title,"header_1":header1,"header_2":header2,"header_3":header3,"content": chunk.page_content})
    return pd.DataFrame(chunk_list)

In [88]:
relative_path = "data/raw/"
Filename = "10Q-MSFT-04-25-2023.pdf"

Markdown = True

ocr_extraction = OcrExtractionDI(relative_path = relative_path+Filename, Markdown=Markdown)
content_map = MdFormatting(ocr_extraction)
content_map.groupby(by=["title",'header_1',"header_2"],sort=False)['content'].count().reset_index()[:30]

,title,header_1,header_2,content
0,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,FORM 10-Q,,1
1,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION,,1
2,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION FORM 10-Q For the Quarte...,,1
3,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,,,1
4,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,COMPREHENSIVE INCOME STATEMENTS,,1
5,PART ! Item 1,BALANCE SHEETS,,1
6,PART ! Item 1,BALANCE SHEETS,CASH FLOWS STATEMENTS,1
7,STOCKHOLDERS' EQUITY STATEMENTS,,,1
8,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Accounting Principles,1
9,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Principles of Consolidation,1
10,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Estimates and Assumptions,1
11,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Financial Instruments,5
12,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 2 - EARNINGS PER SHARE,,1
13,NOTES TO FINANCIAL STATEMENTS (Unaudited),"NOTE 3 - OTHER INCOME (EXPENSE), NET",,1
14,NOTES TO FINANCIAL STATEMENTS (Unaudited),"NOTE 3 - OTHER INCOME (EXPENSE), NET",Net Recognized Gains (Losses) on Investments,5
15,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,,1
16,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Foreign Currencies,1
17,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Interest Rate,1
18,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Equity,1
19,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Credit,1
20,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Credit-Risk-Related Contingent Features,1
21,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 5 - DERIVATIVES,Fair Values of Derivative Instruments,1
22,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 6 - INVENTORIES,,1
23,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 7 - BUSINESS COMBINATIONS,"Nuance Communications, Inc.",1
24,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 7 - BUSINESS COMBINATIONS,"Activision Blizzard, Inc.",1
25,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 8 - GOODWILL,,1
26,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 8 - GOODWILL,NOTE 9 - INTANGIBLE ASSETS,1
27,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 11 - INCOME TAXES,Effective Tax Rate,1
28,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 11 - INCOME TAXES,Uncertain Tax Positions,1
29,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 12 - UNEARNED REVENUE,,1

In [97]:
print(ocr_extraction.content)

# UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington, D.C. 20549


## FORM 10-Q

☒
QUARTERLY REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the Quarterly Period Ended December 31, 2022
OR

☐
TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the Transition Period From
to

Commission File Number 001-37845


## MICROSOFT CORPORATION

WASHINGTON
(STATE OF INCORPORATION)
ONE MICROSOFT WAY, REDMOND, WASHINGTON 98052-6399
(425) 882-8080
www.microsoft.com/investor

91-1144442
(I.R.S. ID)


<table>
<tr>
<th colspan="3">Securities registered pursuant to Section 12(b) of the Act:</th>
</tr>
<tr>
<th>Title of each class</th>
<th>Trading Symbol</th>
<th>Name of exchange on which registered</th>
</tr>
<tr>
<td>Common stock, $0.00000625 par value per share</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
<tr>
<td>3.125% Notes due 2028</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
<tr>
<td>2.625% Notes due 2033</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
</table>


Indicate by check mark whether the registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities Exchange Act of 1934 during the
preceding 12 months (or for such shorter period that the registrant was required to file such reports), and (2) has been subject to such filing requirements for the past
90 days.
☒
Yes
☐
No
Indicate by check mark whether the registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405 of Regulation S-T
(§232.405 of this chapter) during the preceding 12 months (or for such shorter period that the registrant was required to submit such files). Yes
☒ ☐
No

Indicate by check mark whether the registrant is a large accelerated filer, an accelerated filer, a non-accelerated filer, a smaller reporting company, or an emerging
growth company. See the definitions of "large accelerated filer," "accelerated filer," "smaller reporting company," and "emerging growth company" in Rule 12b-2 of the
Exchange Act.
Large Accelerated Filer
Non-accelerated Filer
☐ ☒ ☐

Accelerated Filer
☐
Smaller Reporting Company
Emerging Growth Company
☐

If an emerging growth company, indicate by check mark if the registrant has elected not to use the extended transition period for complying with any new or revised
financial accounting standards provided pursuant to Section 13(a) of the Exchange Act.
☐
☐

Indicate by check mark whether the registrant is a shell company (as defined in Rule 12b-2 of the Exchange Act). Yes
☐
No

☒

Indicate the number of shares outstanding of each of the issuer's classes of common stock, as of the latest practicable date.


<table>
<tr>
<th>Class</th>
<th>Outstanding as of January 19, 2023</th>
</tr>
<tr>
<td>Common Stock, $0.00000625 par value per share</td>
<td>7,443,803,533 shares</td>
</tr>
</table>


<!-- PageBreak -->


## MICROSOFT CORPORATION FORM 10-Q For the Quarter Ended December 31, 2022 INDEX


<table>
<tr>
<th>PART I.</th>
<th colspan="2">FINANCIAL INFORMATION</th>
<th>Page</th>
</tr>
<tr>
<th></th>
<th>Item 1.</th>
<th>Financial Statements</th>
<th></th>
</tr>
<tr>
<td></td>
<td></td>
<td>a) Income Statements for the Three and Six Months Ended December 31, 2022 and 2021</td>
<td>3</td>
</tr>
<tr>
<td colspan="2"></td>
<td>b) Comprehensive Income Statements for the Three and Six Months Ended December 31, 2022 and 2021</td>
<td>4</td>
</tr>
<tr>
<td colspan="2"></td>
<td>c) Balance Sheets as of December 31, 2022 and June 30, 2022</td>
<td>5</td>
</tr>
<tr>
<td colspan="2"></td>
<td>d) Cash Flows Statements for the Three and Six Months Ended December 31, 2022 and 2021</td>
<td>6</td>
</tr>
<tr>
<td colspan="2"></td>
<td>e) Stockholders' Equity Statements for the Three and Six Months Ended December 31, 2022 and 2021</td>
<td>7</td>
</tr>
<tr>
<td></td>
<td></td>
<td>f) Notes to Financial Statements</td>
<td>8</td>
</tr>
<tr>
<td></td>
<td></td>
<td>g) Report of Independent Registered Public Accounting Firm</td>
<td>30</td>
</tr>
<tr>
<td></td>
<td>Item 2.</td>
<td>Management's Discussion and Analysis of Financial Condition and Results of Operations</td>
<td>31</td>
</tr>
<tr>
<td colspan="2">Item 3.</td>
<td>Quantitative and Qualitative Disclosures About Market Risk</td>
<td>49</td>
</tr>
<tr>
<td colspan="2">Item 4.</td>
<td>Controls and Procedures</td>
<td>49</td>
</tr>
<tr>
<td>PART II.</td>
<td colspan="2">OTHER INFORMATION</td>
<td></td>
</tr>
<tr>
<td></td>
<td>Item 1.</td>
<td>Legal Proceedings</td>
<td>50</td>
</tr>
<tr>
<td></td>
<td>Item 1A.</td>
<td>Risk Factors</td>
<td>50</td>
</tr>
<tr>
<td colspan="2">Item 2.</td>
<td>Unregistered Sales of Equity Securities and Use of Proceeds</td>
<td>65</td>
</tr>
<tr>
<td></td>
<td>Item 6.</td>
<td>Exhibits</td>
<td>66</td>
</tr>
<tr>
<td colspan="2">SIGNATURE</td>
<td></td>
<td>67</td>
</tr>
</table>


<!-- PageNumber="2" -->
<!-- PageBreak -->

<!-- PageHeader="PART ! Item 1" -->


# PART I. FINANCIAL INFORMATION ITEM 1. FINANCIAL STATEMENTS INCOME STATEMENTS


<table>
<tr>
<th>(In millions, except per share amounts) (Unaudited)</th>
<th colspan="3">Three Months Ended December 31,</th>
<th>Six Months Ended December 31,</th>
</tr>
<tr>
<th></th>
<th>2022</th>
<th>2021</th>
<th>2022</th>
<th>2021</th>
</tr>
<tr>
<td>Revenue:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Product</td>
<td>$ 16,517</td>
<td>$ 20,779</td>
<td>$ 32,258</td>
<td>$ 37,410</td>
</tr>
<tr>
<td>Service and other</td>
<td>36,230</td>
<td>30,949</td>
<td>70,611</td>
<td>59,635</td>
</tr>
<tr>
<td>Total revenue</td>
<td>52,747</td>
<td>51,728</td>
<td>102,869</td>
<td>97,045</td>
</tr>
<tr>
<td>Cost of revenue:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Product</td>
<td>5,690</td>
<td>6,331</td>
<td>9,992</td>
<td>10,123</td>
</tr>
<tr>
<td>Service and other</td>
<td>11,798</td>
<td>10,629</td>
<td>22,948</td>
<td>20,483</td>
</tr>
<tr>
<td>Total cost of revenue</td>
<td>17,488</td>
<td>16,960</td>
<td>32,940</td>
<td>30,606</td>
</tr>
<tr>
<td>Gross margin</td>
<td>35,259</td>
<td>34,768</td>
<td>69,929</td>
<td>66,439</td>
</tr>
<tr>
<td>Research and development</td>
<td>6,844</td>
<td>5,758</td>
<td>13,472</td>
<td>11,357</td>
</tr>
<tr>
<td>Sales and marketing</td>
<td>5,679</td>
<td>5,379</td>
<td>10,805</td>
<td>9,926</td>
</tr>
<tr>
<td>General and administrative</td>
<td>2,337</td>
<td>1,384</td>
<td>3,735</td>
<td>2,671</td>
</tr>
<tr>
<td>Operating income</td>
<td>20,399</td>
<td>22,247</td>
<td>41,917</td>
<td>42,485</td>
</tr>
<tr>
<td>Other income (expense), net</td>
<td>(60)</td>
<td>268</td>
<td>(6)</td>
<td>554</td>
</tr>
<tr>
<td>Income before income taxes</td>
<td>20,339</td>
<td>22,515</td>
<td>41,911</td>
<td>43,039</td>
</tr>
<tr>
<td>Provision for income taxes</td>
<td>3,914</td>
<td>3,750</td>
<td>7,930</td>
<td>3,769</td>
</tr>
<tr>
<td>Net income</td>
<td>$ 16,425</td>
<td>$ 18,765</td>
<td>$ 33,981</td>
<td>$ 39,270</td>
</tr>
<tr>
<td>Earnings per share:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Basic</td>
<td>$ 2.20</td>
<td>$ 2.50</td>
<td>$ 4.56</td>
<td>$ 5.23</td>
</tr>
<tr>
<td>Diluted</td>
<td>$ 2.20</td>
<td>$ 2.48</td>
<td>$ 4.54</td>
<td>$ 5.19</td>
</tr>
<tr>
<td>Weighted average shares outstanding:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Basic</td>
<td>7,451</td>
<td>7,505</td>
<td>7,454</td>
<td>7,509</td>
</tr>
<tr>
<td>Diluted</td>
<td>7,473</td>
<td>7,555</td>
<td>7,479</td>
<td>7,561</td>
</tr>
</table>


Refer to accompanying notes.

<!-- PageNumber="3" -->
<!-- PageBreak -->

<!-- PageHeader="PART ! Item 1" -->


## COMPREHENSIVE INCOME STATEMENTS


<table>
<tr>
<th>(In millions) (Unaudited)</th>
<th colspan="4">Three Months Ended Six Months Ended December 31, December 31,</th>
</tr>
<tr>
<th></th>
<th>2022</th>
<th>2021</th>
<th>2022</th>
<th>2021</th>
</tr>
<tr>
<td>Net income</td>
<td>$ 16,425</td>
<td>$ 18,765</td>
<td>$ 33,981</td>
<td>$ 39,270</td>
</tr>
<tr>
<td>Other comprehensive income (loss), net of tax:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Net change related to derivatives</td>
<td>(32)</td>
<td>0</td>
<td>(25)</td>
<td>2</td>
</tr>
<tr>
<td>Net change related to investments</td>
<td>348</td>
<td>(743)</td>
<td>(1,549)</td>
<td>(1,165)</td>
</tr>
<tr>
<td>Translation adjustments and other</td>
<td>570</td>
<td>(103)</td>
<td>(205)</td>
<td>(222)</td>
</tr>
<tr>
<td>Other comprehensive income (loss)</td>
<td>886</td>
<td>(846)</td>
<td>(1,779)</td>
<td>(1,385)</td>
</tr>
<tr>
<td>Comprehensive income</td>
<td>$ 17,311</td>
<td>$ 17,919</td>
<td>$ 32,202</td>
<td>$ 37,885</td>
</tr>
</table>


Refer to accompanying notes.

<!-- PageNumber="4" -->
<!-- PageBreak -->


# PART ! Item 1


## BALANCE SHEETS

(In millions) (Unaudited)


<table>
<tr>
<th></th>
<th>December 31, 2022</th>
<th>June 30, 2022</th>
</tr>
<tr>
<td>Assets</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Current assets:</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Cash and cash equivalents</td>
<td>$ 15,646</td>
<td>$ 13,931</td>
</tr>
<tr>
<td>Short-term investments</td>
<td>83,862</td>
<td>90,826</td>
</tr>
<tr>
<td>Total cash, cash equivalents, and short-term investments</td>
<td>99,508</td>
<td>104,757</td>
</tr>
<tr>
<td>Accounts receivable, net of allowance for doubtful accounts of $485 and $633</td>
<td>35,833</td>
<td>44,261</td>
</tr>
<tr>
<td>Inventories</td>
<td>2,980</td>
<td>3,742</td>
</tr>
<tr>
<td>Other current assets</td>
<td>19,502</td>
<td>16,924</td>
</tr>
<tr>
<td>Total current assets</td>
<td>157,823</td>
<td>169,684</td>
</tr>
<tr>
<td>Property and equipment, net of accumulated depreciation of $63,459 and $59,660</td>
<td>82,755</td>
<td>74,398</td>
</tr>
<tr>
<td>Operating lease right-of-use assets</td>
<td>13,624</td>
<td>13,148</td>
</tr>
<tr>
<td>Equity investments</td>
<td>7,097</td>
<td>6,891</td>
</tr>
<tr>
<td>Goodwill</td>
<td>67,905</td>
<td>67,524</td>
</tr>
<tr>
<td>Intangible assets, net</td>
<td>10,354</td>
<td>11,298</td>
</tr>
<tr>
<td>Other long-term assets</td>
<td>24,994</td>
<td>21,897</td>
</tr>
<tr>
<td>Total assets</td>
<td>$ 364,552</td>
<td>$ 364,840</td>
</tr>
<tr>
<td>Liabilities and stockholders' equity</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Current liabilities:</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Accounts payable</td>
<td>$ 15,354</td>
<td>$ 19,000</td>
</tr>
<tr>
<td>Current portion of long-term debt</td>
<td>3,997</td>
<td>2,749</td>
</tr>
<tr>
<td>Accrued compensation</td>
<td>9,030</td>
<td>10,661</td>
</tr>
<tr>
<td>Short-term income taxes</td>
<td>3,553</td>
<td>4,067</td>
</tr>
<tr>
<td>Short-term unearned revenue</td>
<td>36,982</td>
<td>45,538</td>
</tr>
<tr>
<td>Other current liabilities</td>
<td>12,802</td>
<td>13,067</td>
</tr>
<tr>
<td>Total current liabilities</td>
<td>81,718</td>
<td>95,082</td>
</tr>
<tr>
<td>Long-term debt</td>
<td>44,119</td>
<td>47,032</td>
</tr>
<tr>
<td>Long-term income taxes</td>
<td>24,169</td>
<td>26,069</td>
</tr>
<tr>
<td>Long-term unearned revenue</td>
<td>2,644</td>
<td>2,870</td>
</tr>
<tr>
<td>Deferred income taxes</td>
<td>289</td>
<td>230</td>
</tr>
<tr>
<td>Operating lease liabilities</td>
<td>11,998</td>
<td>11,489</td>
</tr>
<tr>
<td>Other long-term liabilities</td>
<td>16,479</td>
<td>15,526</td>
</tr>
<tr>
<td>Total liabilities</td>
<td>181,416</td>
<td>198,298</td>
</tr>
<tr>
<td>Commitments and contingencies</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Stockholders' equity:</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Common stock and paid-in capital - shares authorized 24,000; outstanding 7,447 and 7,464</td>
<td>90,225</td>
<td>86,939</td>
</tr>
<tr>
<td>Retained earnings</td>
<td>99,368</td>
<td>84,281</td>
</tr>
<tr>
<td>Accumulated other comprehensive loss</td>
<td>(6,457)</td>
<td>(4,678)</td>
</tr>
<tr>
<td>Total stockholders' equity</td>
<td>183,136</td>
<td>166,542</td>
</tr>
<tr>
<td>Total liabilities and stockholders' equity</td>
<td>$ 364,552</td>
<td>$ 364,840</td>
</tr>
</table>


Refer to accompanying notes.

<!-- PageNumber="5" -->
<!-- PageBreak -->

<!-- PageHeader="PART I Item 1" -->


# CASH FLOWS STATEMENTS


<table>
<tr>
<th>(In millions) (Unaudited)</th>
<th colspan="4">Three Months Ended Six Months Ended December 31, December 31,</th>
</tr>
<tr>
<th></th>
<th>2022</th>
<th>2021</th>
<th>2022</th>
<th>2021</th>
</tr>
<tr>
<td>Operations</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Net income</td>
<td>$ 16,425</td>
<td>$ 18,765</td>
<td>$ 33,981</td>
<td>$ 39,270</td>
</tr>
<tr>
<td>Adjustments to reconcile net income to net cash from operations:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Depreciation, amortization, and other</td>
<td>3,648</td>
<td>3,496</td>
<td>6,438</td>
<td>6,708</td>
</tr>
<tr>
<td>Stock-based compensation expense</td>
<td>2,538</td>
<td>1,897</td>
<td>4,730</td>
<td>3,599</td>
</tr>
<tr>
<td>Net recognized losses (gains) on investments and derivatives</td>
<td>214</td>
<td>(307)</td>
<td>192</td>
<td>(671)</td>
</tr>
<tr>
<td>Deferred income taxes</td>
<td>(1,305)</td>
<td>183</td>
<td>(2,496)</td>
<td>(5,787)</td>
</tr>
<tr>
<td>Changes in operating assets and liabilities:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Accounts receivable</td>
<td>(3,164)</td>
<td>(5,543)</td>
<td>8,565</td>
<td>4,943</td>
</tr>
<tr>
<td>Inventories</td>
<td>1,305</td>
<td>394</td>
<td>762</td>
<td>(383)</td>
</tr>
<tr>
<td>Other current assets</td>
<td>(392)</td>
<td>830</td>
<td>(724)</td>
<td>1,770</td>
</tr>
<tr>
<td>Other long-term assets</td>
<td>(65)</td>
<td>(908)</td>
<td>(731)</td>
<td>(1,506)</td>
</tr>
<tr>
<td>Accounts payable</td>
<td>(2,058)</td>
<td>235</td>
<td>(3,625)</td>
<td>(236)</td>
</tr>
<tr>
<td>Unearned revenue</td>
<td>(5,186)</td>
<td>(4,343)</td>
<td>(8,508)</td>
<td>(7,228)</td>
</tr>
<tr>
<td>Income taxes</td>
<td>(2,863)</td>
<td>(2,057)</td>
<td>(2,453)</td>
<td>596</td>
</tr>
<tr>
<td>Other current liabilities</td>
<td>1,819</td>
<td>1,745</td>
<td>(2,205)</td>
<td>(2,398)</td>
</tr>
<tr>
<td>Other long-term liabilities</td>
<td>257</td>
<td>93</td>
<td>445</td>
<td>343</td>
</tr>
<tr>
<td>Net cash from operations</td>
<td>11,173</td>
<td>14,480</td>
<td>34,371</td>
<td>39,020</td>
</tr>
<tr>
<td>Financing</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Repayments of debt</td>
<td>(750)</td>
<td>0</td>
<td>(1,750)</td>
<td>(4,826)</td>
</tr>
<tr>
<td>Common stock issued</td>
<td>243</td>
<td>291</td>
<td>818</td>
<td>903</td>
</tr>
<tr>
<td>Common stock repurchased</td>
<td>(5,459)</td>
<td>(7,433)</td>
<td>(11,032)</td>
<td>(15,117)</td>
</tr>
<tr>
<td>Common stock cash dividends paid</td>
<td>(5,066)</td>
<td>(4,652)</td>
<td>(9,687)</td>
<td>(8,858)</td>
</tr>
<tr>
<td>Other, net</td>
<td>(317)</td>
<td>(192)</td>
<td>(581)</td>
<td>(364)</td>
</tr>
<tr>
<td>Net cash used in financing</td>
<td>(11,349)</td>
<td>(11,986)</td>
<td>(22,232)</td>
<td>(28,262)</td>
</tr>
<tr>
<td>Investing</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Additions to property and equipment</td>
<td>(6,274)</td>
<td>(5,865)</td>
<td>(12,557)</td>
<td>(11,675)</td>
</tr>
<tr>
<td>Acquisition of companies, net of cash acquired, and purchases of intangible and other assets</td>
<td>(679)</td>
<td>(850)</td>
<td>(1,028)</td>
<td>(2,056)</td>
</tr>
<tr>
<td>Purchases of investments</td>
<td>(11,599)</td>
<td>(2,505)</td>
<td>(16,612)</td>
<td>(12,814)</td>
</tr>
<tr>
<td>Maturities of investments</td>
<td>6,928</td>
<td>5,253</td>
<td>13,590</td>
<td>14,115</td>
</tr>
<tr>
<td>Sales of investments</td>
<td>4,775</td>
<td>2,895</td>
<td>7,486</td>
<td>8,525</td>
</tr>
<tr>
<td>Other, net</td>
<td>(301)</td>
<td>(89)</td>
<td>(1,161)</td>
<td>(506)</td>
</tr>
<tr>
<td>Net cash used in investing</td>
<td>(7,150)</td>
<td>(1,161)</td>
<td>(10,282)</td>
<td>(4,411)</td>
</tr>
<tr>
<td>Effect of foreign exchange rates on cash and cash equivalents</td>
<td>88</td>
<td>106</td>
<td>(142)</td>
<td>33</td>
</tr>
<tr>
<td>Net change in cash and cash equivalents</td>
<td>(7,238)</td>
<td>1,439</td>
<td>1,715</td>
<td>6,380</td>
</tr>
<tr>
<td>Cash and cash equivalents, beginning of period</td>
<td>22,884</td>
<td>19,165</td>
<td>13,931</td>
<td>14,224</td>
</tr>
<tr>
<td>Cash and cash equivalents, end of period</td>
<td>$ 15,646</td>
<td>$ 20,604</td>
<td>$ 15,646</td>
<td>$ 20,604</td>
</tr>
</table>


Refer to accompanying notes.

<!-- PageNumber="6" -->
<!-- PageBreak -->

<!-- PageHeader="PART I Item 1" -->


# STOCKHOLDERS' EQUITY STATEMENTS


<table>
<tr>
<th>(In millions, except per share amounts) (Unaudited)</th>
<th colspan="4">Three Months Ended Six Months Ended December 31, December 31,</th>
</tr>
<tr>
<th></th>
<th>2022</th>
<th>2021</th>
<th>2022</th>
<th>2021</th>
</tr>
<tr>
<td>Common stock and paid-in capital</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Balance, beginning of period</td>
<td>$ 88,535</td>
<td>$ 83,751</td>
<td>$ 86,939</td>
<td>$ 83,111</td>
</tr>
<tr>
<td>Common stock issued</td>
<td>243</td>
<td>291</td>
<td>818</td>
<td>903</td>
</tr>
<tr>
<td>Common stock repurchased</td>
<td>(1,090)</td>
<td>(1,411)</td>
<td>(2,261)</td>
<td>(3,088)</td>
</tr>
<tr>
<td>Stock-based compensation expense</td>
<td>2,538</td>
<td>1,897</td>
<td>4,730</td>
<td>3,599</td>
</tr>
<tr>
<td>Other, net</td>
<td>(1)</td>
<td>0</td>
<td>(1)</td>
<td>3</td>
</tr>
<tr>
<td>Balance, end of period</td>
<td>90,225</td>
<td>84,528</td>
<td>90,225</td>
<td>84,528</td>
</tr>
<tr>
<td>Retained earnings</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Balance, beginning of period</td>
<td>92,374</td>
<td>66,944</td>
<td>84,281</td>
<td>57,055</td>
</tr>
<tr>
<td>Net income</td>
<td>16,425</td>
<td>18,765</td>
<td>33,981</td>
<td>39,270</td>
</tr>
<tr>
<td>Common stock cash dividends</td>
<td>(5,059)</td>
<td>(4,646)</td>
<td>(10,123)</td>
<td>(9,297)</td>
</tr>
<tr>
<td>Common stock repurchased</td>
<td>(4,372)</td>
<td>(6,018)</td>
<td>(8,771)</td>
<td>(11,983)</td>
</tr>
<tr>
<td>Balance, end of period</td>
<td>99,368</td>
<td>75,045</td>
<td>99,368</td>
<td>75,045</td>
</tr>
<tr>
<td>Accumulated other comprehensive income (loss)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Balance, beginning of period</td>
<td>(7,343)</td>
<td>1,283</td>
<td>(4,678)</td>
<td>1,822</td>
</tr>
<tr>
<td>Other comprehensive income (loss)</td>
<td>886</td>
<td>(846)</td>
<td>(1,779)</td>
<td>(1,385)</td>
</tr>
<tr>
<td>Balance, end of period</td>
<td>(6,457)</td>
<td>437</td>
<td>(6,457)</td>
<td>437</td>
</tr>
<tr>
<td>Total stockholders' equity</td>
<td>$ 183,136</td>
<td>$ 160,010</td>
<td>$ 183,136</td>
<td>$ 160,010</td>
</tr>
<tr>
<td>Cash dividends declared per common share</td>
<td>$ 0.68</td>
<td>$ 0.62</td>
<td>$ 1.36</td>
<td>$ 1.24</td>
</tr>
</table>


Refer to accompanying notes.

<!-- PageNumber="7" -->
<!-- PageBreak -->

<!-- PageHeader="PARTI Item 1" -->


# NOTES TO FINANCIAL STATEMENTS (Unaudited)


## NOTE 1 - ACCOUNTING POLICIES


### Accounting Principles

Our unaudited interim consolidated financial statements and accompanying notes are prepared in accordance with accounting principles
generally accepted in the United States of America ("GAAP"). In the opinion of management, the unaudited interim consolidated financial
statements reflect all adjustments of a normal recurring nature that are necessary for a fair presentation of the results for the interim periods
presented. Interim results are not necessarily indicative of results for a full year. The information included in this Form 10-Q should be read in
conjunction with information included in the Microsoft Corporation fiscal year 2022 Form 10-K filed with the U.S. Securities and Exchange
Commission on July 28, 2022.


### Principles of Consolidation

The consolidated financial statements include the accounts of Microsoft Corporation and its subsidiaries. Intercompany transactions and
balances have been eliminated.


### Estimates and Assumptions


In [89]:
relative_path = "data/raw/"
Filename = "10Q-MSFT-01-24-2023.pdf"

Markdown = True

ocr_extraction = OcrExtractionDI(relative_path = relative_path+Filename, Markdown=Markdown)
content_map = MdFormatting(ocr_extraction)
content_map.groupby(by=["title",'header_1',"header_2"],sort=False)['content'].count().reset_index()[:30]

,title,header_1,header_2,content
0,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,FORM 10-Q,,1
1,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION,,1
2,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION FORM 10-Q For the Quarte...,,1
3,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,,,1
4,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,COMPREHENSIVE INCOME STATEMENTS,,1
5,PART ! Item 1,BALANCE SHEETS,,1
6,CASH FLOWS STATEMENTS,,,1
7,STOCKHOLDERS' EQUITY STATEMENTS,,,1
8,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Accounting Principles,1
9,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Principles of Consolidation,1
10,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Estimates and Assumptions,1
11,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 1 - ACCOUNTING POLICIES,Financial Instruments,5
12,NOTES TO FINANCIAL STATEMENTS (Unaudited),NOTE 2 - EARNINGS PER SHARE,,1
13,"NOTE 3 - OTHER INCOME (EXPENSE), NET",,,1
14,"NOTE 3 - OTHER INCOME (EXPENSE), NET",Net Recognized Gains (Losses) on Investments,,1
15,"NOTE 3 - OTHER INCOME (EXPENSE), NET",Net Recognized Gains (Losses) on Investments,NOTE 4 - INVESTMENTS,3
16,NOTE 5 - DERIVATIVES,,,1
17,NOTE 5 - DERIVATIVES,Foreign Currencies,,1
18,NOTE 5 - DERIVATIVES,Interest Rate,,1
19,NOTE 5 - DERIVATIVES,Equity,,1
20,NOTE 5 - DERIVATIVES,Credit,,1
21,NOTE 5 - DERIVATIVES,Credit-Risk-Related Contingent Features,,1
22,NOTE 5 - DERIVATIVES,Fair Values of Derivative Instruments,,1
23,NOTE 5 - DERIVATIVES,Fair Values of Derivative Instruments,NOTE 6 - INVENTORIES,1
24,NOTE 7 - BUSINESS COMBINATIONS,"Nuance Communications, Inc.",,1
25,NOTE 7 - BUSINESS COMBINATIONS,"Activision Blizzard, Inc.",,1
26,NOTE 8 - GOODWILL,,,1
27,NOTE 9 - INTANGIBLE ASSETS,,,1
28,NOTE 10 - DEBT,,,1
29,NOTE 11 - INCOME TAXES,Effective Tax Rate,,1

In [102]:
content_map.loc[3]

title        PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...
header_1
header_2
header_3
content      <table>\n<tr>\n<th>(In millions, except per sh...
token_len                                                 1091
Name: 3, dtype: object

In [101]:
print(content_map.content[3])

<table>
<tr>
<th>(In millions, except per share amounts) (Unaudited)</th>
<th colspan="3">Three Months Ended December 31,</th>
<th>Six Months Ended December 31,</th>
</tr>
<tr>
<th></th>
<th>2022</th>
<th>2021</th>
<th>2022</th>
<th>2021</th>
</tr>
<tr>
<td>Revenue:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Product</td>
<td>$ 16,517</td>
<td>$ 20,779</td>
<td>$ 32,258</td>
<td>$ 37,410</td>
</tr>
<tr>
<td>Service and other</td>
<td>36,230</td>
<td>30,949</td>
<td>70,611</td>
<td>59,635</td>
</tr>
<tr>
<td>Total revenue</td>
<td>52,747</td>
<td>51,728</td>
<td>102,869</td>
<td>97,045</td>
</tr>
<tr>
<td>Cost of revenue:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Product</td>
<td>5,690</td>
<td>6,331</td>
<td>9,992</td>
<td>10,123</td>
</tr>
<tr>
<td>Service and other</td>
<td>11,798</td>
<td>10,629</td>
<td>22,948</td>
<td>20,483</td>
</tr>
<tr>
<td>Total cost of revenue</td>
<td>17,488</td>
<td>16,960</td>
<td>32,940</td>
<td>30,606</td>
</tr>
<tr>
<td>Gross margin</td>
<td>35,259</td>
<td>34,768</td>
<td>69,929</td>
<td>66,439</td>
</tr>
<tr>
<td>Research and development</td>
<td>6,844</td>
<td>5,758</td>
<td>13,472</td>
<td>11,357</td>
</tr>
<tr>
<td>Sales and marketing</td>
<td>5,679</td>
<td>5,379</td>
<td>10,805</td>
<td>9,926</td>
</tr>
<tr>
<td>General and administrative</td>
<td>2,337</td>
<td>1,384</td>
<td>3,735</td>
<td>2,671</td>
</tr>
<tr>
<td>Operating income</td>
<td>20,399</td>
<td>22,247</td>
<td>41,917</td>
<td>42,485</td>
</tr>
<tr>
<td>Other income (expense), net</td>
<td>(60)</td>
<td>268</td>
<td>(6)</td>
<td>554</td>
</tr>
<tr>
<td>Income before income taxes</td>
<td>20,339</td>
<td>22,515</td>
<td>41,911</td>
<td>43,039</td>
</tr>
<tr>
<td>Provision for income taxes</td>
<td>3,914</td>
<td>3,750</td>
<td>7,930</td>
<td>3,769</td>
</tr>
<tr>
<td>Net income</td>
<td>$ 16,425</td>
<td>$ 18,765</td>
<td>$ 33,981</td>
<td>$ 39,270</td>
</tr>
<tr>
<td>Earnings per share:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Basic</td>
<td>$ 2.20</td>
<td>$ 2.50</td>
<td>$ 4.56</td>
<td>$ 5.23</td>
</tr>
<tr>
<td>Diluted</td>
<td>$ 2.20</td>
<td>$ 2.48</td>
<td>$ 4.54</td>
<td>$ 5.19</td>
</tr>
<tr>
<td>Weighted average shares outstanding:</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Basic</td>
<td>7,451</td>
<td>7,505</td>
<td>7,454</td>
<td>7,509</td>
</tr>
<tr>
<td>Diluted</td>
<td>7,473</td>
<td>7,555</td>
<td>7,479</td>
<td>7,561</td>
</tr>
</table>
Refer to accompanying notes.
<!-- PageNumber="3" -->
<!-- PageBreak -->
<!-- PageHeader="PART ! Item 1" -->

In [92]:
def num_tokens_from_string(string: str) -> int:
    encoding = tiktoken.encoding_for_model("gpt-4o")
    num_tokens = len(encoding.encode(string))
    return num_tokens

In [94]:
content_map['token_len'] = content_map.content.apply(num_tokens_from_string)

In [95]:
content_map

,title,header_1,header_2,header_3,content,token_len
0,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,FORM 10-Q,,,☒\nQUARTERLY REPORT PURSUANT TO SECTION 13 OR ...,96
1,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION,,,WASHINGTON\n(STATE OF INCORPORATION)\nONE MICR...,692
2,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,MICROSOFT CORPORATION FORM 10-Q For the Quarte...,,,"<table>\n<tr>\n<th>PART I.</th>\n<th colspan=""...",670
3,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,,,,"<table>\n<tr>\n<th>(In millions, except per sh...",1091
4,PART I. FINANCIAL INFORMATION ITEM 1. FINANCIA...,COMPREHENSIVE INCOME STATEMENTS,,,<table>\n<tr>\n<th>(In millions) (Unaudited)</...,396
...,...,...,...,...,...,...
130,ITEM 6. EXHIBITS,15.1 Letter regarding unaudited interim financ...,,,31.1\nCertification of Chief Executive Officer...,282
131,SIGNATURE,,,,Pursuant to the requirements of the Securities...,323
132,CERTIFICATION,,,,"I, Satya Nadella, certify that: \n1\. I have ...",655
133,CERTIFICATION,CERTIFICATION,,,"I, Amy E. Hood, certify that: \n1\. I have re...",660
134,CERTIFICATION PURSUANT TO SECTION 906 OF THE S...,,,,In connection with the Quarterly Report of Mic...,484

#### Using Summarization API